### PR TITLE
add @gugod's twtxt feed

### PR DESCRIPTION
**Pull request by gugod**

### CODE REVIEW

**Review by prologic — APPROVED** [review]

**Comment by gugod** [comment]
not quite sure why it's conflicting again. perhaps I branched off from a old commit

**Comment by gugod** [comment]
evidently I forked this repo at commit 9efe643 and just left it alone..... :-)

**Comment by prologic** [comment]
That's much better! Merged!

**Comment by prologic** [comment]
Now someone ust needs to help us write new bots for this :D --> https://github.com/jointwt/twtxt/issues/329

**Pull request merged**
